uploads = []

[[generated]]
id = "9WYw3jzQdRE8hBSKpVznT"
uri = "file://artifacts/sms-forwarder/assets/images/icon.png"
type = "image"
title = "sms forwarder icon"

[[outputs]]
id = "fDmbJv3aewQm22JAKoiDp"
uri = "file://google-apps-script/gmail-utr-forwarder.txt"
type = "text"
title = "Gmail UTR Auto-Forwarder Script"

[[outputs]]
id = "pnNxYsUe_2xBzBZOkylsG"
uri = "file://attached_assets/generated_audio/birthday_celebration.mp3"
type = "audio"
title = "birthday_celebration"

[[outputs]]
id = "gjz_4GJeF9ow3C2nnNgWb"
uri = "file://attached_assets/generated_audio/birthday_melody.mp3"
type = "audio"
title = "birthday_melody"

[[outputs]]
id = "xr1yoN4lI585hiUcIC9NN"
uri = "file://attached_assets/generated_audio/happy_birthday_tune.mp3"
type = "audio"
title = "happy_birthday_tune"
