import { Link } from "wouter";
import { motion } from "framer-motion";
import { HeartPulse, ArrowLeft } from "lucide-react";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2 className="text-xl font-bold text-white mb-4">{title}</h2>
      <div className="text-white/55 leading-relaxed space-y-3 text-sm">{children}</div>
    </div>
  );
}

export default function Terms() {
  return (
    <div className="min-h-screen w-full overflow-hidden bg-background text-foreground">
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] rounded-full bg-primary/20 blur-[120px]" />
        <div className="absolute bottom-[-20%] right-[-10%] w-[60%] h-[60%] rounded-full bg-secondary/20 blur-[150px]" />
      </div>

      <div className="relative z-10 container mx-auto px-6 pt-12 pb-24 max-w-2xl">
        <header className="flex items-center gap-4 mb-16">
          <Link href="/" className="flex items-center gap-2 text-white/40 hover:text-white/70 transition-colors text-sm">
            <ArrowLeft className="w-4 h-4" />
            Back
          </Link>
          <div className="flex items-center gap-2 ml-auto">
            <div className="bg-gradient-to-tr from-primary to-secondary p-2 rounded-xl">
              <HeartPulse className="w-5 h-5 text-white" />
            </div>
            <span className="text-lg font-bold tracking-tight text-white">HeartSync AI</span>
          </div>
        </header>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-4xl font-extrabold text-white mb-2">Terms & Conditions</h1>
          <p className="text-white/35 text-sm mb-12">Last updated: April 2026</p>

          <div className="bg-white/[0.03] border border-white/[0.08] rounded-3xl p-8 mb-8">

            <Section title="1. About HeartSync AI">
              <p>
                HeartSync AI ("we", "us", or "our") is an AI-powered relationship intelligence
                service that generates personalised date preparation reports ("Reports") based on
                information you provide. The service is operated from India and is intended for
                users aged 18 and above.
              </p>
            </Section>

            <Section title="2. Eligibility">
              <p>
                By creating an account or using HeartSync AI, you confirm that you are at least 18
                years old and have the legal capacity to enter into these terms. The service is
                currently available to residents of India only.
              </p>
            </Section>

            <Section title="3. Your Account">
              <p>
                You are responsible for keeping your account credentials secure. HeartSync AI
                supports sign-in via email/password and mobile OTP (One-Time Password). You must
                not share your account with others or use it for any commercial purpose without
                prior written permission.
              </p>
            </Section>

            <Section title="4. The Service">
              <p>
                HeartSync AI uses large language model (LLM) technology to generate Reports. Each
                Report contains four sections: Inner Game (mindset & energy), Opening Gambit
                (conversation starters), IQ Questions (curiosity-driven questions), and
                Conversation Closers (warm sign-off suggestions).
              </p>
              <p>
                Reports are personalised based on the scenario you describe and are generated fresh
                each time. Reports expire 48 hours after generation.
              </p>
            </Section>

            <Section title="5. AI-Generated Content Disclaimer">
              <p>
                All Reports are generated by artificial intelligence and are intended for
                entertainment and self-improvement purposes only. HeartSync AI makes no guarantee
                that following any advice in a Report will lead to a specific outcome.
              </p>
              <p>
                You are solely responsible for how you use the information in your Reports.
                HeartSync AI is not a licensed psychological or relationship counselling service.
              </p>
            </Section>

            <Section title="6. Credits & Paid Packs">
              <p>
                Your first Report is free. Additional Reports require credits. Credits are sold in
                packs (e.g. 5 reports for ₹99) via the in-app payment flow. Credits are
                non-transferable and tied to your account.
              </p>
              <p>
                Credits do not expire as long as your account remains active. If your account is
                deleted or suspended for a violation of these terms, unused credits will be
                forfeited.
              </p>
            </Section>

            <Section title="7. Acceptable Use">
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-1 pl-2">
                <li>Use HeartSync AI for any unlawful, harmful, or deceptive purpose.</li>
                <li>Attempt to reverse-engineer, scrape, or reproduce the service or its outputs at scale.</li>
                <li>Use the service to harass, stalk, or harm any individual.</li>
                <li>Submit false or misleading payment information.</li>
              </ul>
              <p>
                We reserve the right to suspend or terminate accounts that violate these rules
                without prior notice.
              </p>
            </Section>

            <Section title="8. Limitation of Liability">
              <p>
                To the maximum extent permitted under applicable Indian law, HeartSync AI and its
                operators shall not be liable for any indirect, incidental, or consequential
                damages arising from use of the service. Our total aggregate liability to you shall
                not exceed the amount you paid for credits in the 30 days preceding the claim.
              </p>
            </Section>

            <Section title="9. Changes to Terms">
              <p>
                We may update these Terms from time to time. Continued use of the service after
                changes are posted constitutes your acceptance of the updated Terms. We will note
                the "Last updated" date at the top of this page.
              </p>
            </Section>

            <Section title="10. Governing Law">
              <p>
                These Terms are governed by the laws of India. Any disputes shall be subject to
                the exclusive jurisdiction of the courts of Gurugram (Gurgaon), Haryana, India.
              </p>
            </Section>

            <Section title="11. Contact">
              <p>
                For any queries related to these Terms, please contact us at{" "}
                <a
                  href="mailto:heartsyncai2026@gmail.com"
                  className="text-primary hover:underline"
                >
                  heartsyncai2026@gmail.com
                </a>
                .
              </p>
            </Section>
          </div>

          <div className="bg-white/[0.03] border border-white/[0.08] rounded-3xl p-8">
            <h1 className="text-2xl font-bold text-white mb-2">Refund & Cancellation Policy</h1>
            <p className="text-white/35 text-sm mb-8">Last updated: April 2026</p>

            <Section title="1. Credit Packs — No Refund on Used Credits">
              <p>
                Once a credit pack is purchased and credits have been used to generate one or more
                Reports, those credits are considered consumed and are non-refundable.
              </p>
            </Section>

            <Section title="2. Unused Credits — Refund Eligibility">
              <p>
                If you have purchased a credit pack and have not used any credits from that
                specific purchase, you may request a full refund within 7 days of the purchase
                date by contacting us at{" "}
                <a href="mailto:heartsyncai2026@gmail.com" className="text-primary hover:underline">
                  heartsyncai2026@gmail.com
                </a>{" "}
                with your registered email address and transaction reference.
              </p>
              <p>
                Partial refunds (e.g. for partially used packs) are not available.
              </p>
            </Section>

            <Section title="3. Technical Failures">
              <p>
                If your payment was successfully deducted but credits were not added to your
                account due to a technical error on our end, please contact us within 48 hours
                with your payment screenshot or UPI transaction ID. We will investigate and either
                credit your account or issue a full refund within 5–7 business days.
              </p>
            </Section>

            <Section title="4. Subscription / Auto-renewal">
              <p>
                HeartSync AI does not currently offer subscriptions or auto-renewing plans. All
                purchases are one-time credit packs. There is nothing to cancel.
              </p>
            </Section>

            <Section title="5. How to Request a Refund">
              <p>Email us at{" "}
                <a href="mailto:heartsyncai2026@gmail.com" className="text-primary hover:underline">
                  heartsyncai2026@gmail.com
                </a>{" "}
                with:
              </p>
              <ul className="list-disc list-inside space-y-1 pl-2">
                <li>Subject line: "Refund Request — HeartSync AI"</li>
                <li>Your registered email address</li>
                <li>Date and amount of the transaction</li>
                <li>UPI transaction ID or payment screenshot</li>
                <li>Reason for the refund request</li>
              </ul>
              <p>
                We will respond within 2 business days and process eligible refunds within 5–7
                business days to the original payment method.
              </p>
            </Section>
          </div>

          <div className="mt-8 text-center">
            <p className="text-white/25 text-sm">
              HeartSync AI · Gurgaon, India ·{" "}
              <Link href="/contact" className="hover:text-white/50 transition-colors">Contact Us</Link>
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
